-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 15:35:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Iva
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Iva` ;

-- -----------------------------------------------------
-- Schema Iva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Iva` ;
USE `Iva` ;

-- -----------------------------------------------------
-- Table `Iva`.`Contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Contacto` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Contacto` (
  `codContacto` INT(11) NOT NULL,
  `email` VARCHAR(15) NULL,
  `TelFixo` INT(11) NULL,
  `TelCelular` INT(11) NOT NULL,
  PRIMARY KEY (`codContacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Endereco` (
  `CodEndereco` INT NOT NULL,
  `Distrito` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(15) NOT NULL,
  `Avenida` VARCHAR(20) NULL,
  `Rua` VARCHAR(20) NULL,
  PRIMARY KEY (`CodEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `Iva`.`fornecedor` (
  `codFornecedor` INT(11) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(30) NOT NULL,
  `Telefone` INT(12) NOT NULL,
  `Endereco_CodEndereco` INT NOT NULL,
  PRIMARY KEY (`codFornecedor`, `Endereco_CodEndereco`),
  CONSTRAINT `fk_fornecedor_Endereco1`
    FOREIGN KEY (`Endereco_CodEndereco`)
    REFERENCES `Iva`.`Endereco` (`CodEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`tipoproduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`tipoproduto` ;

CREATE TABLE IF NOT EXISTS `Iva`.`tipoproduto` (
  `CodTipoProduto` INT(11) NOT NULL,
  `DescrTipoProduto` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CodTipoProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`produto` ;

CREATE TABLE IF NOT EXISTS `Iva`.`produto` (
  `CodProduto` INT(11) NOT NULL,
  `Descr` VARCHAR(20) NOT NULL,
  `Quantidade` INT(11) NULL DEFAULT NULL,
  `PrecoUnit` DECIMAL(11,2) NULL DEFAULT NULL,
  `CodTipoProduto` INT(11) NOT NULL,
  `Finalidade` ENUM('C', 'V') NOT NULL,
  PRIMARY KEY (`CodProduto`),
  CONSTRAINT `TipoProduto`
    FOREIGN KEY (`CodTipoProduto`)
    REFERENCES `Iva`.`tipoproduto` (`CodTipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`usuario` ;

CREATE TABLE IF NOT EXISTS `Iva`.`usuario` (
  `CodUsuario` INT(11) NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CodUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Cliente` (
  `codCliente` INT(11) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(30) NOT NULL,
  `Telefone` INT(12) NOT NULL,
  `Endereco_CodEndereco` INT NOT NULL,
  PRIMARY KEY (`codCliente`),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_CodEndereco`)
    REFERENCES `Iva`.`Endereco` (`CodEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`venda` ;

CREATE TABLE IF NOT EXISTS `Iva`.`venda` (
  `CodVenda` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `PrecoTotal` DECIMAL(10,0) NULL,
  `Cliente_codCliente` INT(11) NOT NULL,
  PRIMARY KEY (`CodVenda`, `Cliente_codCliente`),
  CONSTRAINT `fk_venda_Cliente1`
    FOREIGN KEY (`Cliente_codCliente`)
    REFERENCES `Iva`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Nota` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Nota` (
  `CodNota` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `Tipo` ENUM('C', 'D') NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `Descr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodNota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Factura` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Factura` (
  `CodFactura` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `DataValidade` DATETIME NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `desconto` DECIMAL(10,0) NOT NULL,
  `Nota_CodNota` INT NOT NULL,
  `venda_CodVenda` INT(11) NOT NULL,
  `venda_Cliente_codCliente` INT(11) NOT NULL,
  PRIMARY KEY (`CodFactura`, `Nota_CodNota`, `venda_CodVenda`, `venda_Cliente_codCliente`),
  CONSTRAINT `fk_Factura_Nota1`
    FOREIGN KEY (`Nota_CodNota`)
    REFERENCES `Iva`.`Nota` (`CodNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_venda1`
    FOREIGN KEY (`venda_CodVenda` , `venda_Cliente_codCliente`)
    REFERENCES `Iva`.`venda` (`CodVenda` , `Cliente_codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`fornecedor_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`fornecedor_has_produto` ;

CREATE TABLE IF NOT EXISTS `Iva`.`fornecedor_has_produto` (
  `fornecedor_codFornecedor` INT(11) NOT NULL,
  `produto_CodProduto` INT(11) NOT NULL,
  PRIMARY KEY (`fornecedor_codFornecedor`, `produto_CodProduto`),
  CONSTRAINT `fk_fornecedor_has_produto1_fornecedor1`
    FOREIGN KEY (`fornecedor_codFornecedor`)
    REFERENCES `Iva`.`fornecedor` (`codFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_produto1_produto1`
    FOREIGN KEY (`produto_CodProduto`)
    REFERENCES `Iva`.`produto` (`CodProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`venda_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`venda_has_produto` ;

CREATE TABLE IF NOT EXISTS `Iva`.`venda_has_produto` (
  `venda_CodVenda` INT(11) NOT NULL,
  `produto_CodProduto` INT(11) NOT NULL,
  PRIMARY KEY (`venda_CodVenda`, `produto_CodProduto`),
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`venda_CodVenda`)
    REFERENCES `Iva`.`venda` (`CodVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`produto_CodProduto`)
    REFERENCES `Iva`.`produto` (`CodProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Recibo` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Recibo` (
  `CodRecibo` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `Factura_CodFactura` INT NOT NULL,
  `Factura_Nota_CodNota` INT NOT NULL,
  `Factura_venda_CodVenda` INT(11) NOT NULL,
  `Factura_venda_Cliente_codCliente` INT(11) NOT NULL,
  PRIMARY KEY (`CodRecibo`),
  CONSTRAINT `fk_Recibo_Factura1`
    FOREIGN KEY (`Factura_CodFactura` , `Factura_Nota_CodNota` , `Factura_venda_CodVenda` , `Factura_venda_Cliente_codCliente`)
    REFERENCES `Iva`.`Factura` (`CodFactura` , `Nota_CodNota` , `venda_CodVenda` , `venda_Cliente_codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`VD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`VD` ;

CREATE TABLE IF NOT EXISTS `Iva`.`VD` (
  `CodVenda` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `desconto` DECIMAL(10,0) NOT NULL,
  `venda_CodVenda` INT(11) NOT NULL,
  `venda_Cliente_codCliente` INT(11) NOT NULL,
  PRIMARY KEY (`CodVenda`),
  CONSTRAINT `fk_VD_venda1`
    FOREIGN KEY (`venda_CodVenda` , `venda_Cliente_codCliente`)
    REFERENCES `Iva`.`venda` (`CodVenda` , `Cliente_codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Contas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Contas` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Contas` (
  `CodContas` INT NOT NULL,
  `Classes` VARCHAR(45) NULL,
  `Debito` VARCHAR(45) NULL,
  `Credito` VARCHAR(45) NULL,
  `Saldo` VARCHAR(45) NULL,
  `RegraDeMovimento` VARCHAR(45) NULL,
  PRIMARY KEY (`CodContas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
