-- MySQL Script generated by MySQL Workbench
-- Sat Feb 15 18:31:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Iva
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Iva` ;

-- -----------------------------------------------------
-- Schema Iva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Iva` ;
USE `Iva` ;

-- -----------------------------------------------------
-- Table `Iva`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Endereco` (
  `CodEndereco` INT NOT NULL,
  `Distrito` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(15) NOT NULL,
  `Avenida` VARCHAR(20) NULL,
  `Rua` VARCHAR(20) NULL,
  PRIMARY KEY (`CodEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `Iva`.`fornecedor` (
  `CodFornecedor` INT(11) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Nuit` INT(9) NOT NULL,
  `NrEdficio` INT NOT NULL,
  `CaixaPostal` INT NOT NULL,
  `CodPostal` INT NOT NULL,
  `CodEndereco` INT NOT NULL,
  PRIMARY KEY (`CodFornecedor`),
  CONSTRAINT `fk_fornecedor_Endereco1`
    FOREIGN KEY (`CodEndereco`)
    REFERENCES `Iva`.`Endereco` (`CodEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`ContactoF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`ContactoF` ;

CREATE TABLE IF NOT EXISTS `Iva`.`ContactoF` (
  `codContacto` INT(11) NOT NULL,
  `email` VARCHAR(15) NULL,
  `TelFixo` INT(11) NULL,
  `TelCelular` INT(11) NOT NULL,
  `CodFornecedor` INT(11) NOT NULL,
  PRIMARY KEY (`codContacto`),
  CONSTRAINT `fk_ContactoC_fornecedor1`
    FOREIGN KEY (`CodFornecedor`)
    REFERENCES `Iva`.`fornecedor` (`CodFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`TipoArtigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`TipoArtigo` ;

CREATE TABLE IF NOT EXISTS `Iva`.`TipoArtigo` (
  `CodTipoArtigo` INT(11) NOT NULL,
  `Descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CodTipoArtigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Artigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Artigo` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Artigo` (
  `CodArtigo` INT(11) NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(100) NOT NULL,
  `Quantidade` INT(11) NULL DEFAULT NULL,
  `PrecoUnit` DECIMAL(15,2) NOT NULL,
  `Taxa` ENUM('Iva', 'Insecao') NOT NULL,
  `CodTipoArtigo` INT(11) NOT NULL,
  `Artigo` VARCHAR(45) NULL,
  `Unidade` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  `Peso` VARCHAR(45) NULL,
  `Moeda` VARCHAR(45) NULL,
  PRIMARY KEY (`CodArtigo`),
  CONSTRAINT `fk_Artigo_TipoArtigo1`
    FOREIGN KEY (`CodTipoArtigo`)
    REFERENCES `Iva`.`TipoArtigo` (`CodTipoArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`usuario` ;

CREATE TABLE IF NOT EXISTS `Iva`.`usuario` (
  `CodUsuario` INT(11) NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CodUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`venda` ;

CREATE TABLE IF NOT EXISTS `Iva`.`venda` (
  `CodVenda` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `PrecoTotal` DECIMAL(15,2) NOT NULL,
  `CodCliente` INT(11) NOT NULL,
  `Iva` DECIMAL(15,2) NULL,
  PRIMARY KEY (`CodVenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Factura` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Factura` (
  `CodFactura` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `DataValidade` DATETIME NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `desconto` DECIMAL(15,2) NOT NULL,
  `CodVenda` INT(11) NOT NULL,
  PRIMARY KEY (`CodFactura`),
  CONSTRAINT `fk_Factura_venda1`
    FOREIGN KEY (`CodVenda`)
    REFERENCES `Iva`.`venda` (`CodVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Cliente` (
  `CodCliente` INT(11) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Nuit` INT NULL,
  `NrEdificio` INT NULL,
  `CodPostal` INT NULL,
  `CaixaPostal` INT NULL,
  `CodEndereco` INT NOT NULL,
  PRIMARY KEY (`CodCliente`),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`CodEndereco`)
    REFERENCES `Iva`.`Endereco` (`CodEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Nota` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Nota` (
  `CodNota` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `Tipo` ENUM('C', 'D') NOT NULL,
  `Valor` DECIMAL(15,2) NOT NULL,
  `Descr` VARCHAR(45) NOT NULL,
  `Iva` DECIMAL(15,2) NOT NULL,
  `CodFactura` INT NOT NULL,
  PRIMARY KEY (`CodNota`),
  CONSTRAINT `fk_Nota_Factura1`
    FOREIGN KEY (`CodFactura`)
    REFERENCES `Iva`.`Factura` (`CodFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Recibo` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Recibo` (
  `CodRecibo` INT NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`CodRecibo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`VD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`VD` ;

CREATE TABLE IF NOT EXISTS `Iva`.`VD` (
  `CodVd` INT NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `desconto` DECIMAL(15,2) NOT NULL,
  `CodVenda` INT(11) NOT NULL,
  `DataEmissao` DATE NOT NULL,
  PRIMARY KEY (`CodVd`),
  CONSTRAINT `fk_VD_venda1`
    FOREIGN KEY (`CodVenda`)
    REFERENCES `Iva`.`venda` (`CodVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Classe` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Classe` (
  `CodClasse` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CodClasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iva`.`Contas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Contas` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Contas` (
  `CodContas` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Tipo` ENUM('A', 'C', 'P', 'F', 'G') NOT NULL,
  `Debito` DECIMAL(15,2) NOT NULL,
  `Credito` DECIMAL(15,2) NOT NULL,
  `Saldo` DECIMAL(15,2) NOT NULL,
  `Nrconta` INT NOT NULL,
  `CodClasse` INT NOT NULL,
  PRIMARY KEY (`CodContas`),
  CONSTRAINT `fk_Contas_Classe1`
    FOREIGN KEY (`CodClasse`)
    REFERENCES `Iva`.`Classe` (`CodClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iva`.`Subconta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Subconta` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Subconta` (
  `codSubconta` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Debito` DECIMAL(15,2) NOT NULL,
  `Credito` DECIMAL(15,2) NOT NULL,
  `Saldo` DECIMAL(15,2) NOT NULL,
  `NrSubConta` INT NOT NULL,
  `CodContas` INT NOT NULL,
  PRIMARY KEY (`codSubconta`),
  CONSTRAINT `fk_Subconta_Contas1`
    FOREIGN KEY (`CodContas`)
    REFERENCES `Iva`.`Contas` (`CodContas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iva`.`Artigo_has_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Artigo_has_fornecedor` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Artigo_has_fornecedor` (
  `CodArtigo` INT(11) NOT NULL,
  `CodFornecedor` INT(11) NOT NULL,
  PRIMARY KEY (`CodArtigo`, `CodFornecedor`),
  CONSTRAINT `fk_Artigo_has_fornecedor_Artigo1`
    FOREIGN KEY (`CodArtigo`)
    REFERENCES `Iva`.`Artigo` (`CodArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artigo_has_fornecedor_fornecedor1`
    FOREIGN KEY (`CodFornecedor`)
    REFERENCES `Iva`.`fornecedor` (`CodFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`ContactoC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`ContactoC` ;

CREATE TABLE IF NOT EXISTS `Iva`.`ContactoC` (
  `CodContacto` INT(11) NOT NULL,
  `email` VARCHAR(15) NULL,
  `TelFixo` INT(11) NULL,
  `TelCelular` INT(11) NOT NULL,
  `CodCliente` INT(11) NOT NULL,
  PRIMARY KEY (`CodContacto`),
  CONSTRAINT `fk_ContactoC_Cliente1`
    FOREIGN KEY (`CodCliente`)
    REFERENCES `Iva`.`Cliente` (`CodCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Recibo_has_Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Recibo_has_Factura` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Recibo_has_Factura` (
  `CodRecibo` INT NOT NULL,
  `CodFactura` INT NOT NULL,
  PRIMARY KEY (`CodRecibo`, `CodFactura`),
  CONSTRAINT `fk_Recibo_has_Factura_Recibo1`
    FOREIGN KEY (`CodRecibo`)
    REFERENCES `Iva`.`Recibo` (`CodRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_has_Factura_Factura1`
    FOREIGN KEY (`CodFactura`)
    REFERENCES `Iva`.`Factura` (`CodFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`venda_has_Artigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`venda_has_Artigo` ;

CREATE TABLE IF NOT EXISTS `Iva`.`venda_has_Artigo` (
  `CodVenda` INT(11) NOT NULL,
  `CodArtigo` INT(11) NOT NULL,
  PRIMARY KEY (`CodVenda`, `CodArtigo`),
  CONSTRAINT `fk_venda_has_Artigo_venda1`
    FOREIGN KEY (`CodVenda`)
    REFERENCES `Iva`.`venda` (`CodVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_Artigo_Artigo1`
    FOREIGN KEY (`CodArtigo`)
    REFERENCES `Iva`.`Artigo` (`CodArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Iva`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Stock` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `Custo` INT NOT NULL,
  `Total` INT NOT NULL,
  `Documento` ENUM('E', 'S') NOT NULL,
  PRIMARY KEY (`idStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iva`.`Documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Iva`.`Documento` ;

CREATE TABLE IF NOT EXISTS `Iva`.`Documento` (
  `idDocumento` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocumento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
