/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.BDconexao;
import Model.Dao.FornecedorDAO;
import Model.Dao.ProdutoDAO;
import Model.Entidade.Fornecedor;
import Model.Entidade.Produto;
import Model.Entidade.Tabela;
import Model.Entidade.Tipoproduto;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author JEQUE
 */
public class FormProduto extends javax.swing.JFrame {

    
    Produto pmode=new Produto();
    ProdutoDAO pdao=new ProdutoDAO();
    BDconexao conex=new BDconexao();
    Connection con;
    int flag=0;
     
    
    
    
    /**
     * Creates new form PaginaFornecedor
     */
     CardLayout cardLayout;
    public FormProduto() {
        initComponents();
        preencherFornecedor();
        preencherTipo();
        cardLayout=(CardLayout)(jPanelPrincipal.getLayout());
        PreencherTabela("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor NATURAL JOIN produto NATURAL join tipoproduto");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jButtonPesquisa = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecUnit = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelLateral = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Produtos");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProdutosLayout = new javax.swing.GroupLayout(jPanelProdutos);
        jPanelProdutos.setLayout(jPanelProdutosLayout);
        jPanelProdutosLayout.setHorizontalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProdutosLayout.setVerticalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelProdutos, "telaProduto");

        jPanelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNome.setText("Descricao:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tipo");

        jTextFieldDescr.setEnabled(false);
        jTextFieldDescr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescrActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fornecedor:");

        jComboBoxFornecedor.setEnabled(false);
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });

        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jTextFieldQtd.setEnabled(false);
        jTextFieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdActionPerformed(evt);
            }
        });

        jLabel4.setText("Artigo:");

        jLabel5.setText("Preco");

        jTextFieldPrecUnit.setEnabled(false);
        jTextFieldPrecUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecUnitActionPerformed(evt);
            }
        });

        jTextFieldCod.setEnabled(false);

        jLabel3.setText("ID");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxFornecedor, 0, 156, Short.MAX_VALUE)
                            .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrecUnit))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPrecUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelCadastro, "telaCadastro");

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(114, 41, 530, 280);

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo1.setText("Produtos");
        getContentPane().add(jLabelTitulo1);
        jLabelTitulo1.setBounds(274, 11, 110, 16);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jPanelLateral.setBackground(new java.awt.Color(250, 250, 250));

        jButtonNovo.setBackground(new java.awt.Color(235, 235, 235));
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(235, 235, 235));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 350);

        setSize(new java.awt.Dimension(666, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void preencherTipo(){
    con=BDconexao.getconnection();
    conex.executaSql("Select *from tipoProduto order by DescrTipoProduto");
        try {
            conex.rs.first();
            
               jComboBoxTipo.removeAllItems();
            do{
                jComboBoxTipo.addItem(conex.rs.getString("DescrTipoProduto"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preecher Tipo");
        }
     BDconexao.fecharConexao(con);
    }
    
      public void preencherFornecedor(){
    con=BDconexao.getconnection();
    conex.executaSql("Select *from Fornecedor order by Nome");
        try {
            conex.rs.first();
            
               jComboBoxFornecedor.removeAllItems();
            do{
                jComboBoxFornecedor.addItem(conex.rs.getString("Nome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preecher Fornecedor");
        }
     BDconexao.fecharConexao(con);
    }
    public Fornecedor pegarFornecedor(){
       con=BDconexao.getconnection();
       Fornecedor fo=new Fornecedor();
       conex.executaSql("select *from Fornecedor where Nome='"+jComboBoxFornecedor.getSelectedItem()+"'");
       
        try {
            conex.rs.first();
            fo.setCodFornecedor(conex.rs.getInt("CodFornecedor"));
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       BDconexao.fecharConexao(con);
    return fo;
    }
    
     public Tipoproduto pegarTipo(){
       con=BDconexao.getconnection();
        Tipoproduto tp=new Tipoproduto();
       conex.executaSql("select *from tipoproduto where DescrTipoProduto='"+jComboBoxTipo.getSelectedItem()+"'");
       
        try {
            conex.rs.first();
            tp.setCodTipoProduto(conex.rs.getInt("CodTipoProduto"));
            tp.setDescrTipoProduto("DescrTipoProduto");
        } catch (SQLException ex) {
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       BDconexao.fecharConexao(con);
    return tp;
    }
    private void jTextFieldDescrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescrActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       flag=1;
       
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
       jTextFieldDescr.setEnabled(true);
       jTextFieldPrecUnit.setEnabled(true);
       jTextFieldQtd.setEnabled(true);
       jComboBoxFornecedor.setEnabled(true);
       jComboBoxTipo.setEnabled(true);
       //jTextFieldPesquisa.setEnabled(false);
       //jButtonPesquisa.setEnabled(false);
       cardLayout.show(jPanelPrincipal,"telaCadastro");
       
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag=2;
          cardLayout.show(jPanelPrincipal,"telaCadastro");
         jButtonSalvar.setEnabled(true);
         jButtonCancelar.setEnabled(true);
         
         jButtonPesquisa.setEnabled(false);
         jTextFieldPesquisa.setEnabled(false);
       jTextFieldDescr.setEnabled(true);
       jTextFieldPrecUnit.setEnabled(true);
       jTextFieldQtd.setEnabled(true);
       jComboBoxFornecedor.setEnabled(true);
       jComboBoxTipo.setEnabled(true);
       
       jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      
      if(flag==1){
       pmode.setDescr(jTextFieldDescr.getText());
       pmode.setQuantidade(Integer.parseInt(jTextFieldQtd.getText()));
       pmode.setPrecoUnit(Double.parseDouble(jTextFieldPrecUnit.getText()));
       pmode.setCodFornecedor((pegarFornecedor().getCodFornecedor()));
       pmode.setCodTipoProduto(pegarTipo().getCodTipoProduto());
       
       pdao.inserir(pmode);
       jTextFieldDescr.setText("");
       jTextFieldPrecUnit.setText("");
       jTextFieldQtd.setText("");
       jComboBoxFornecedor.setSelectedItem("");
       jComboBoxTipo.setSelectedItem("");
       
       jButtonSalvar.setEnabled(false);
       //jButtonCancelar.setEnabled(false);
     //  jButtonNovo.setEnabled(true);
       //jTextFieldDescr.setEnabled(false);
      // jTextFieldPrecUnit.setEnabled(false);
      // jTextFieldQtd.setEnabled(false);
      // jComboBoxFornecedor.setEnabled(false);
     //  jComboBoxTipo.setEnabled(false);
      
       PreencherTabela("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor NATURAL JOIN produto NATURAL join tipoproduto");
     
      }else{
       pmode.setCodProduto(Integer.parseInt(jTextFieldCod.getText()));
       pmode.setDescr(jTextFieldDescr.getText());
       pmode.setQuantidade(Integer.parseInt(jTextFieldQtd.getText()));
       pmode.setPrecoUnit(Double.parseDouble(jTextFieldPrecUnit.getText()));
       pmode.setCodFornecedor((pegarFornecedor().getCodFornecedor()));
       pmode.setCodTipoProduto(pegarTipo().getCodTipoProduto());
       
       pdao.update(pmode);
       
       jTextFieldDescr.setText("");
       jTextFieldPrecUnit.setText("");
       jTextFieldQtd.setText("");
       jComboBoxFornecedor.setSelectedItem("");
       jComboBoxTipo.setSelectedItem("");
       
       jButtonNovo.setEnabled(true);
       jButtonSalvar.setEnabled(false);
       jButtonCancelar.setEnabled(false);
       jButtonEditar.setEnabled(false);
       jButtonExcluir.setEnabled(false);
       jButtonPesquisa.setEnabled(true);
       
       jTextFieldPesquisa.setEnabled(true);
       jTextFieldDescr.setEnabled(false);
       jTextFieldPrecUnit.setEnabled(false);
       jTextFieldQtd.setEnabled(false);
       jComboBoxFornecedor.setEnabled(false);
       jComboBoxTipo.setEnabled(false);
       PreencherTabela("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor NATURAL JOIN produto NATURAL join tipoproduto");
    
    
    
    }
       
       
       
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTextFieldPrecUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecUnitActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
        /*
        String s=null;
        
        FornecedorDAO fdao=new FornecedorDAO();
        Fornecedor fmode=new Fornecedor();
        List<Fornecedor> f=fdao.listar();
     
        for(Fornecedor fo:f)
           s+=","+fo.getNome();
        */
     //jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[]{s}));
    
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jTextFieldCod.setText("");
        jTextFieldDescr.setEnabled(false);
        jTextFieldQtd.setEnabled(false);
        jTextFieldPrecUnit.setEnabled(false);
        jComboBoxTipo.setEnabled(false); 
        jComboBoxFornecedor.setEnabled(false);
       jButtonPesquisa.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jTextFieldDescr.setText("");
       jTextFieldPrecUnit.setText("");
       jTextFieldQtd.setText("");
       jComboBoxFornecedor.setSelectedItem("");
       jComboBoxTipo.setSelectedItem("");
       cardLayout.show(jPanelPrincipal,"telaProduto");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
     String nome=""+jTableProduto.getValueAt(jTableProduto.getSelectedRow(),1);
       con=BDconexao.getconnection();
       
       conex.executaSql("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
               + "NATURAL JOIN produto NATURAL join tipoproduto where descr='"+nome+"'");
       try {
           conex.rs.first();
           jTextFieldCod.setText(String.valueOf(conex.rs.getInt("CodProduto")));
            jTextFieldDescr.setText(conex.rs.getString("Descr"));
           jTextFieldQtd.setText(conex.rs.getString("Artigo"));
         jComboBoxFornecedor.setSelectedItem(conex.rs.getString("Nome"));
           jTextFieldPrecUnit.setText(String.valueOf(conex.rs.getDouble("PrecoUnit")));
           jComboBoxTipo.setSelectedItem(conex.rs.getString("DescrTipoProduto"));
         
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,"Erro Ao preecher do MauseClicked");
       }
       BDconexao.fecharConexao(con);
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta=0;
        resposta=JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir");
        if(resposta==JOptionPane.YES_OPTION){
            pmode.setCodProduto(Integer.parseInt(jTextFieldCod.getText()));
            pdao.delete(pmode);}
        PreencherTabela("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
               + "NATURAL JOIN produto NATURAL join tipoproduto");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
         jButtonPesquisa.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
         jTextFieldCod.setText("");
        jTextFieldDescr.setText("");
        jTextFieldQtd.setText("");
        jTextFieldPrecUnit.setText("");
      
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        pmode.setPesquisa(jTextFieldPesquisa.getText());
        PreencherTabela("SELECT CodProduto,Descr,Artigo,Nome,PrecoUnit,DescrTipoProduto from Fornecedor NATURAL JOIN produto NATURAL join tipoproduto where Descr like'%"+pmode.getPesquisa()+"%'");
        jTextFieldPesquisa.setText("");
    }//GEN-LAST:event_jButtonPesquisaActionPerformed
      public void PreencherTabela(String sql){
    ArrayList dados=new ArrayList();
    String[] colunas=new String[]{"ID","Descr","Artigo","Fornecedor","PrecUnit","Tipo"};
    con=BDconexao.getconnection();
    conex.executaSql(sql);
    try{
    conex.rs.first();
    do{
       dados.add(new Object[]{conex.rs.getInt("CodProduto"),conex.rs.getString("Descr"),
       conex.rs.getString("Artigo"),conex.rs.getString("Nome"),conex.rs.getInt("PrecoUnit"),
       conex.rs.getString("DescrTipoProduto")});
      
    }while(conex.rs.next());
    }catch(SQLException ex){
    
       JOptionPane.showMessageDialog(null,"Busque novamente");
    } 
    Tabela modelo=new Tabela(dados,colunas);
  
   
    jTableProduto.setModel(modelo);
    jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(45);
    jTableProduto.getColumnModel().getColumn(0).setResizable(false);
     jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(180);
    jTableProduto.getColumnModel().getColumn(1).setResizable(false);
     jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(80);
    jTableProduto.getColumnModel().getColumn(2).setResizable(false);
     jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(90);
    jTableProduto.getColumnModel().getColumn(3).setResizable(false);
     jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(60);
    jTableProduto.getColumnModel().getColumn(4).setResizable(false);
     jTableProduto.getColumnModel().getColumn(5).setPreferredWidth(90);
    jTableProduto.getColumnModel().getColumn(5).setResizable(false);
    jTableProduto.getTableHeader().setReorderingAllowed(false);
    jTableProduto.setAutoResizeMode(jTableProduto.AUTO_RESIZE_OFF);
    jTableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
    BDconexao.fecharConexao(con);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDescr;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPrecUnit;
    private javax.swing.JTextField jTextFieldQtd;
    // End of variables declaration//GEN-END:variables
}
