/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.BDconexao;
import Model.Dao.FornecedorDAO;
import Model.Entidade.Fornecedor;
//import Model.Entidade.Tabela;
import static View.PaginaLogin.usuario;
import java.awt.CardLayout;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author JEQUE
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    
   FornecedorDAO fdao=new FornecedorDAO();
   Fornecedor fmode=new Fornecedor();
   BDconexao conex=new BDconexao();
   Connection con;
   int n;
   
   
   int flag=0;
    CardLayout cardLayout;
    
    
    public PaginaInicial() {
        initComponents();
        cardLayout=(CardLayout)(jPanelPrincipal.getLayout());
     //jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[]{usuario.getNome(), "Perfil", "Sair"}));
        upTime(jLabel11);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelMenuVendas = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jButton_Gravar = new javax.swing.JButton();
        jButton_Novo = new javax.swing.JButton();
        jButton_Imprimir = new javax.swing.JButton();
        jButton_Copiar = new javax.swing.JButton();
        jButton_Procurar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Vendas = new javax.swing.JPanel();
        jScrollPane_Entidade = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox_Entidade = new javax.swing.JComboBox<>();
        jComboBox_Entidade1 = new javax.swing.JComboBox<>();
        jPanel_TabelaVendas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_Valores = new javax.swing.JPanel();
        jTextField_Mercadorias = new javax.swing.JTextField();
        jTextField_DescontoFinanceiro = new javax.swing.JTextField();
        jTextField_IVA = new javax.swing.JTextField();
        jTextField_Outros = new javax.swing.JTextField();
        jTextField_Subtotal = new javax.swing.JTextField();
        jTextField_Total = new javax.swing.JTextField();
        jLabel_Mercadorias = new javax.swing.JLabel();
        jLabel_Desconto = new javax.swing.JLabel();
        jLabel_Iva = new javax.swing.JLabel();
        jLabel_Outros = new javax.swing.JLabel();
        jLabel_Subtotal = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jSpinner_dataEmissao = new javax.swing.JSpinner();
        jSpinner_dataVencimento = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_TermosPagamento = new javax.swing.JPanel();
        jPanelVendas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jbNovaFactura = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jbNovaVenda = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCompras = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableFacturas1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanelFacturar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanelFornecedor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableForncedor = new javax.swing.JTable();
        jButtonPesquisa = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jPanelInicial = new javax.swing.JPanel();
        jLabelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonVendas = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jButtonfornecedor = new javax.swing.JButton();
        jButtonEstatistica = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonNova = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCopiar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonFeramentas = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemCatProd = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jButton_Home.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\home.png")); // NOI18N
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jButton_Gravar.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Gravar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\gravar.png")); // NOI18N
        jButton_Gravar.setText("Gravar");
        jButton_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GravarActionPerformed(evt);
            }
        });

        jButton_Novo.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/novo.png"))); // NOI18N
        jButton_Novo.setText("Novo");
        jButton_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NovoActionPerformed(evt);
            }
        });

        jButton_Imprimir.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\imprimir.png")); // NOI18N
        jButton_Imprimir.setText("Imprimir");
        jButton_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirActionPerformed(evt);
            }
        });

        jButton_Copiar.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Copiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\copiar.png")); // NOI18N
        jButton_Copiar.setText("Copiar");
        jButton_Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CopiarActionPerformed(evt);
            }
        });

        jButton_Procurar.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton_Procurar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\procurar.png")); // NOI18N
        jButton_Procurar.setText("Procurar");
        jButton_Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProcurarActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Arial Nova Light", 0, 15)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Ivapoint\\Icons\\cancelar.png")); // NOI18N
        jButton14.setText("Cancelar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelMenuVendasLayout = new javax.swing.GroupLayout(jPanelMenuVendas);
        jPanelMenuVendas.setLayout(jPanelMenuVendasLayout);
        jPanelMenuVendasLayout.setHorizontalGroup(
            jPanelMenuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Gravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Imprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Copiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Procurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addContainerGap())
        );
        jPanelMenuVendasLayout.setVerticalGroup(
            jPanelMenuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuVendasLayout.createSequentialGroup()
                .addGroup(jPanelMenuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMenuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Gravar)
                        .addComponent(jButton_Novo)
                        .addComponent(jButton_Imprimir)
                        .addComponent(jButton_Copiar)
                        .addComponent(jButton_Procurar)
                        .addComponent(jButton14)
                        .addComponent(jButton_Home)))
                .addContainerGap())
        );

        jInternalFrame1.getContentPane().add(jPanelMenuVendas);
        jPanelMenuVendas.setBounds(0, 0, 740, 30);

        jPanel6.setLayout(new java.awt.CardLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 0, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane_Entidade.setViewportView(jTextArea1);

        jComboBox_Entidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Entidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EntidadeActionPerformed(evt);
            }
        });

        jComboBox_Entidade1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Entidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Entidade1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Artigo", "Quantidade", "Descriçao", "Taxa", "Preço Unit.", "IVA", "Valor"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel_TabelaVendasLayout = new javax.swing.GroupLayout(jPanel_TabelaVendas);
        jPanel_TabelaVendas.setLayout(jPanel_TabelaVendasLayout);
        jPanel_TabelaVendasLayout.setHorizontalGroup(
            jPanel_TabelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        jPanel_TabelaVendasLayout.setVerticalGroup(
            jPanel_TabelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        jPanel_Valores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel_Valores.setForeground(new java.awt.Color(204, 204, 204));

        jTextField_DescontoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DescontoFinanceiroActionPerformed(evt);
            }
        });

        jTextField_Subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SubtotalActionPerformed(evt);
            }
        });

        jTextField_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TotalActionPerformed(evt);
            }
        });

        jLabel_Mercadorias.setText("Merc. / Serv.");

        jLabel_Desconto.setText("Desc.");

        jLabel_Iva.setText("IVA");

        jLabel_Outros.setText("Outros");

        jLabel_Subtotal.setText("Subtotal");

        jLabel_Total.setText("Total");

        jSpinner_dataEmissao.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1581270531876L), null, null, java.util.Calendar.DAY_OF_MONTH));

        jSpinner_dataVencimento.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setText("Data de Emiss.");

        jLabel3.setText("Data de Venc.");

        jLabel4.setText("Doc. Nr.:");

        javax.swing.GroupLayout jPanel_ValoresLayout = new javax.swing.GroupLayout(jPanel_Valores);
        jPanel_Valores.setLayout(jPanel_ValoresLayout);
        jPanel_ValoresLayout.setHorizontalGroup(
            jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ValoresLayout.createSequentialGroup()
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ValoresLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ValoresLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_dataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ValoresLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_ValoresLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_dataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Outros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Iva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Desconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Mercadorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Mercadorias, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_DescontoFinanceiro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_IVA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Outros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Subtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel_ValoresLayout.setVerticalGroup(
            jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ValoresLayout.createSequentialGroup()
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_dataEmissao)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_dataVencimento)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner4)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel_ValoresLayout.createSequentialGroup()
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Mercadorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Mercadorias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DescontoFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Desconto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Iva)
                            .addComponent(jTextField_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Outros)
                    .addComponent(jTextField_Outros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Subtotal)
                    .addComponent(jTextField_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Total))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel_VendasLayout = new javax.swing.GroupLayout(jPanel_Vendas);
        jPanel_Vendas.setLayout(jPanel_VendasLayout);
        jPanel_VendasLayout.setHorizontalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TabelaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_VendasLayout.createSequentialGroup()
                .addGroup(jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_Entidade, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(jComboBox_Entidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Entidade1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Valores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel_VendasLayout.setVerticalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_VendasLayout.createSequentialGroup()
                        .addComponent(jComboBox_Entidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_Entidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Entidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Valores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_TabelaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendas", jPanel_Vendas);

        javax.swing.GroupLayout jPanel_TermosPagamentoLayout = new javax.swing.GroupLayout(jPanel_TermosPagamento);
        jPanel_TermosPagamento.setLayout(jPanel_TermosPagamentoLayout);
        jPanel_TermosPagamentoLayout.setHorizontalGroup(
            jPanel_TermosPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel_TermosPagamentoLayout.setVerticalGroup(
            jPanel_TermosPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Termos de Pagamento", jPanel_TermosPagamento);

        jPanel6.add(jTabbedPane1, "card2");

        jInternalFrame1.getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 50, 760, 460);

        jPanelVendas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artigo", "Descricao", "descricao", "Iva", "Preco/Unidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFacturas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jbNovaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jbNovaFactura.setOpaque(false);
        jbNovaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaFacturaActionPerformed(evt);
            }
        });

        jLabel19.setText("nova factura");

        jButton3.setText("Pesuisa");

        jbNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jbNovaVenda.setOpaque(false);
        jbNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaVendaActionPerformed(evt);
            }
        });

        jLabel18.setText("nova venda");

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jbNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(164, 164, 164)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasLayout.createSequentialGroup()
                .addGroup(jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbNovaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jLabel18))
                    .addComponent(jbNovaVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestao de Facturas");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Hora");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 440, 110, 15);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelCompras.setBackground(new java.awt.Color(255, 255, 255));

        jTableFacturas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artigo", "Descricao", "descricao", "Iva", "Preco/Unidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableFacturas1);

        jButton4.setText("Pesuisa");

        javax.swing.GroupLayout jPanelComprasLayout = new javax.swing.GroupLayout(jPanelCompras);
        jPanelCompras.setLayout(jPanelComprasLayout);
        jPanelComprasLayout.setHorizontalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComprasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanelComprasLayout.setVerticalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComprasLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelCompras, "telaCompras");

        jPanelFacturar.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setText("Enviar");

        jButton11.setText("Voltar");

        javax.swing.GroupLayout jPanelFacturarLayout = new javax.swing.GroupLayout(jPanelFacturar);
        jPanelFacturar.setLayout(jPanelFacturarLayout);
        jPanelFacturarLayout.setHorizontalGroup(
            jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacturarLayout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(25, 25, 25))
        );
        jPanelFacturarLayout.setVerticalGroup(
            jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacturarLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelFacturar, "telaFacturar");

        jPanelFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableForncedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jTableForncedor.setOpaque(false);
        jTableForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableForncedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableForncedor);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Capturar.PNG"))); // NOI18N
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFornecedorLayout = new javax.swing.GroupLayout(jPanelFornecedor);
        jPanelFornecedor.setLayout(jPanelFornecedorLayout);
        jPanelFornecedorLayout.setHorizontalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPanelFornecedorLayout.setVerticalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisa))
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelFornecedor, "telaFornecedor");

        jPanelInicial.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFundo.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addComponent(jLabelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(754, 754, 754)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelInicial, "telaInicial");

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(200, 50, 750, 408);

        jPanel2.setBackground(new java.awt.Color(220, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jButtonVendas.setBackground(new java.awt.Color(201, 201, 201));
        jButtonVendas.setText("Vendas");
        jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVendas);
        jButtonVendas.setBounds(0, 0, 200, 32);

        jButtonCompras.setBackground(new java.awt.Color(201, 201, 201));
        jButtonCompras.setText("Compras");
        jButtonCompras.setFocusable(false);
        jButtonCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCompras);
        jButtonCompras.setBounds(0, 30, 200, 30);

        jButtonfornecedor.setBackground(new java.awt.Color(201, 201, 201));
        jButtonfornecedor.setText("Fornecedores");
        jButtonfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonfornecedor);
        jButtonfornecedor.setBounds(0, 60, 200, 30);

        jButtonEstatistica.setBackground(new java.awt.Color(201, 201, 201));
        jButtonEstatistica.setText("Estatistica");
        jPanel2.add(jButtonEstatistica);
        jButtonEstatistica.setBounds(0, 90, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-2, 50, 200, 140);

        jPanel3.setBackground(new java.awt.Color(220, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jButtonNova.setToolTipText("Nova factura");
        jButtonNova.setOpaque(false);
        jButtonNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        jButtonSalvar.setOpaque(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/copy.png"))); // NOI18N
        jButtonCopiar.setOpaque(false);
        jButtonCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        jButton6.setOpaque(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jButton7.setOpaque(false);

        jButtonFeramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/settings.png"))); // NOI18N
        jButtonFeramentas.setOpaque(false);
        jButtonFeramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeramentasActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(235, 235, 235));
        jButtonHome.setText("Home");
        jButtonHome.setFocusable(false);
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setOpaque(false);
        jButtonHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jComboBoxUsuario.setBackground(new java.awt.Color(235, 235, 235));
        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Perfil", "Sair" }));
        jComboBoxUsuario.setOpaque(false);
        jComboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButtonCancelar.setOpaque(false);

        jLabel12.setText("salvar");

        jLabel13.setText("nova");

        jLabel14.setText("Copiar");

        jLabelImprimir.setText("Imprimir");

        jLabel16.setText("Cancelar");

        jLabel17.setText("Ferramentas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHome)
                .addGap(146, 146, 146)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jButtonNova, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelImprimir)
                .addGap(32, 32, 32)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(24, 24, 24)
                .addComponent(jButtonFeramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonHome)
                                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonFeramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNova, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 950, 40);

        jPanel5.setBackground(new java.awt.Color(220, 250, 250));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 950, 480);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu7.setText("file");

        jMenu1.setText("Cadastros");

        jMenuItemUsuario.setText("Usuarios");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuario);

        jMenuItemFornecedor.setText("Fornecedores");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFornecedor);

        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProduto);

        jMenuItemCatProd.setText("Categoria de produtos");
        jMenuItemCatProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCatProdActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCatProd);

        jMenu7.add(jMenu1);

        jMenuItem3.setText("sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Operacoes");

        jMenu2.setText("Facturas ");
        jMenu6.add(jMenu2);

        jMenu3.setText("Fornecedores");
        jMenu6.add(jMenu3);

        jMenu4.setText("Compra");
        jMenu6.add(jMenu4);

        jMenu5.setText("Venda");
        jMenu6.add(jMenu5);

        jMenuBar1.add(jMenu6);

        jMenuSair.setText("Ajuda");

        jMenuItem2.setText("Pagina Inicial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem2);

        jMenuItem1.setText("Acerca");
        jMenuSair.add(jMenuItem1);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(966, 129));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
      FormUsuario telaU=new FormUsuario();
      telaU.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemCatProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCatProdActionPerformed
       FormCategoria telaC=new FormCategoria();
       telaC.setVisible(true);
    }//GEN-LAST:event_jMenuItemCatProdActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
       FormFornecedor telaF=new FormFornecedor();
       telaF.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        FormProduto telaP=new FormProduto();
        telaP.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jTableForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableForncedorMouseClicked
        /*String nome=""+jTableForncedor.getValueAt(jTableForncedor.getSelectedRow(),1);
        con=BDconexao.getconnection();
        conex.executaSql("Select *from Fornecedor where Nome='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldCod.setText(String.valueOf(conex.rs.getInt("CodFornecedor")));
            jTextFieldNome.setText(conex.rs.getString("Nome"));
            jTextFieldEndereco.setText(conex.rs.getString("Endereco"));
            jTextFieldTelefone.setText(String.valueOf(conex.rs.getInt("Telefone")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro Ao preecher do MauseClicked");
        }
        BDconexao.fecharConexao(con);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);*/

    }//GEN-LAST:event_jTableForncedorMouseClicked

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        fmode.setPesquisa(jTextFieldPesquisa.getText());
        //Fornecedor model=fdao.BuscaFornecedor(fmode);
        jTextFieldPesquisa.setText("");
        PreencherTabela("Select *from Fornecedor where nome like'%"+fmode.getPesquisa()+"%'");
        /**jTextFieldNome.setText(model.getNome());
        jTextFieldEndereco.setText(model.getEndereco());
        jTextFieldTelefone.setText(String.valueOf(model.getTelefone()));*/

    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       FormEmpresa telaE=new FormEmpresa();
       telaE.setVisible(true);
               

        /*flag=1;
        jButtonSalvar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);

        jTextFieldCod.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldTelefone.setText("");

        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisa.setEnabled(false);*/
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfornecedorActionPerformed
       cardLayout.show(jPanelPrincipal,"telaFornecedor");
       PreencherTabela("Select *from Fornecedor order by Nome");
    }//GEN-LAST:event_jButtonfornecedorActionPerformed

    private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
        cardLayout.show(jPanelPrincipal,"telaVendas");
    }//GEN-LAST:event_jButtonVendasActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed
        cardLayout.show(jPanelPrincipal,"telaCompras");
       
        
    }//GEN-LAST:event_jButtonComprasActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
     jTextAreaEmpresa.setText("");
        fmode.setPesquisa(""+jComboBoxFornecedor.getSelectedItem());
        Fornecedor f=fdao.BuscaFornecedor(fmode);
        
       jTextAreaEmpresa.insert( f.getEndereco(), jTextAreaEmpresa.getCaretPosition());
       jTextAreaEmpresa.append("\n");
       jTextAreaEmpresa.insert( String.valueOf(f.getTelefone()),jTextAreaEmpresa.getCaretPosition());
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        String nome=""+jTableProduto.getValueAt(jTableProduto.getSelectedRow(),1);
        con=BDconexao.getconnection();

        conex.executaSql("SELECT CodProduto,Descr,CodFornecedor,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
            + "NATURAL JOIN produto NATURAL join tipoproduto where descr='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldArtigo.setText(String.valueOf(conex.rs.getInt("CodProduto")));
            jTextFieldProduto.setText(conex.rs.getString("Descr"));
            jTextFieldQtd.setText("1");
            // jComboBoxFornecedor.setSelectedItem(conex.rs.getString("Nome"));
            jTextFieldPrecUnit.setText(String.valueOf(conex.rs.getDouble("PrecoUnit")));
            jTextFieldTipo.setText(conex.rs.getString("DescrTipoProduto"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro Ao preecher do MauseClicked");
        }
        BDconexao.fecharConexao(con);
    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jButtonPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisa1ActionPerformed
        fmode.setPesquisa(jTextFieldPesquisa1.getText());
       jTextFieldPesquisa1.setText("");
        PreencherTabelaProduto("SELECT CodProduto,Descr,CodFornecedor,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
               + "NATURAL JOIN produto NATURAL join tipoproduto where descr like '%"+fmode.getPesquisa()+"'");
        
    }//GEN-LAST:event_jButtonPesquisa1ActionPerformed
  
       
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        cardLayout.show(jPanelPrincipal,"telaInicial");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cardLayout.show(jPanelPrincipal,"telaFacturar");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioActionPerformed
       switch (jComboBoxUsuario.getSelectedIndex()) {
            case 2:
                
                dispose();
               PaginaLogin p=new PaginaLogin();
               p.setVisible(rootPaneCheckingEnabled);
                break;
        }
    }//GEN-LAST:event_jComboBoxUsuarioActionPerformed

    private void jComboBoxFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorItemStateChanged
       jTextAreaEmpresa.setText("");
        fmode.setPesquisa(""+jComboBoxFornecedor.getSelectedItem());
        Fornecedor f=fdao.BuscaFornecedor(fmode);
        
       jTextAreaEmpresa.insert( f.getEndereco(), jTextAreaEmpresa.getCaretPosition());
       jTextAreaEmpresa.append("\n");
       jTextAreaEmpresa.insert( String.valueOf(f.getTelefone()),jTextAreaEmpresa.getCaretPosition());
    }//GEN-LAST:event_jComboBoxFornecedorItemStateChanged

    private void jButtonNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaActionPerformed
        cardLayout.show(jPanelPrincipal,"telaNovaFactura");
        preencherFornecedor();
    }//GEN-LAST:event_jButtonNovaActionPerformed

    private void jButtonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCopiarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       cardLayout.show(jPanelPrincipal,"telaInicial");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonFeramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeramentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeramentasActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jbNovaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaFacturaActionPerformed
       cardLayout.show(jPanelPrincipal,"telaNovaFactura");
        preencherFornecedor();
    }//GEN-LAST:event_jbNovaFacturaActionPerformed

    private void jbNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNovaVendaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         
       
         
         
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
               float a=Float.parseFloat(jTextFieldQtd.getText());
               float b=Float.parseFloat(jTextFieldPrecUnit.getText());
                String str=""+a*b;
               jTextFieldSubTotal.setText(str);
               jTextFieldTotal.setText(jTextFieldSubTotal.getText());
                                             
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTextFieldDiscontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiscontoActionPerformed
       
       jTextFieldTotal.setText(jTextFieldSubTotal.getText());
        
    }//GEN-LAST:event_jTextFieldDiscontoActionPerformed

    private void jTextField_DescontoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DescontoFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DescontoFinanceiroActionPerformed
     public void upTime(JLabel jlHora) {
        new Thread() {
            
            @Override
            public void run() {
                while (true) {
                    try {
                        jlHora.setText(new Time(System.currentTimeMillis()).toString());
                        sleep(1000);
                    } catch (InterruptedException e) {
                        JOptionPane.showMessageDialog(jlHora, "Erro actualizar a hoara, Erro F006");
                    }
                }
            }
        }.start();
    }
    
    
    public void PreencherTabela(String sql){
    ArrayList dados=new ArrayList();
    String[] colunas=new String[]{"ID","Nome","Endereco","Telefone"};
    con=BDconexao.getconnection();
    conex.executaSql(sql);
    try{
    conex.rs.first();
    do{
       dados.add(new Object[]{conex.rs.getInt("CodFornecedor"),conex.rs.getString("Nome"),
       conex.rs.getString("Endereco"),conex.rs.getInt("Telefone")});
      
    }while(conex.rs.next());
    }catch(SQLException ex){
    
       JOptionPane.showMessageDialog(null,"Busque novamente");
    } 
    Tabela modelo=new Tabela(dados,colunas);
  
   
    jTableForncedor.setModel(modelo);
    jTableForncedor.getColumnModel().getColumn(0).setPreferredWidth(80);
    jTableForncedor.getColumnModel().getColumn(0).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(1).setPreferredWidth(241);
    jTableForncedor.getColumnModel().getColumn(1).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(2).setPreferredWidth(300);
    jTableForncedor.getColumnModel().getColumn(2).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(3).setPreferredWidth(80);
    jTableForncedor.getColumnModel().getColumn(3).setResizable(false);
    jTableForncedor.getTableHeader().setReorderingAllowed(false);
    jTableForncedor.setAutoResizeMode(jTableForncedor.AUTO_RESIZE_OFF);
    jTableForncedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
    BDconexao.fecharConexao(con);
    }
     public void PreencherTabelaProduto(String sql){
    ArrayList dados=new ArrayList();
    String[] colunas=new String[]{"ID","Descr","CodFornecedor","Fornecedor","PrecUnit","Tipo"};
    con=BDconexao.getconnection();
    conex.executaSql(sql);
    try{
    conex.rs.first();
    do{
       dados.add(new Object[]{conex.rs.getInt("CodProduto"),conex.rs.getString("Descr"),
       conex.rs.getString("CodFornecedor"),conex.rs.getString("Nome"),conex.rs.getInt("PrecoUnit"),
       conex.rs.getString("DescrTipoProduto")});
      
    }while(conex.rs.next());
    }catch(SQLException ex){
    
       JOptionPane.showMessageDialog(null,"Busque novamente");
    } 
    Tabela modelo=new Tabela(dados,colunas);
  
   
    jTableProduto.setModel(modelo);
    jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(60);
    jTableProduto.getColumnModel().getColumn(0).setResizable(false);
     jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(250);
    jTableProduto.getColumnModel().getColumn(1).setResizable(false);
     jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
    jTableProduto.getColumnModel().getColumn(2).setResizable(false);
     jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(110);
    jTableProduto.getColumnModel().getColumn(3).setResizable(false);
     jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(80);
    jTableProduto.getColumnModel().getColumn(4).setResizable(false);
     jTableProduto.getColumnModel().getColumn(5).setPreferredWidth(110);
    jTableProduto.getColumnModel().getColumn(5).setResizable(false);
    jTableProduto.getTableHeader().setReorderingAllowed(false);
    jTableProduto.setAutoResizeMode(jTableProduto.AUTO_RESIZE_OFF);
    jTableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
    BDconexao.fecharConexao(con);
    }
    
    public void preencherFornecedor(){
    con=BDconexao.getconnection();
    conex.executaSql("Select *from Fornecedor order by Nome");
        try {
            conex.rs.first();
            
               jComboBoxFornecedor.removeAllItems();
            do{
                jComboBoxFornecedor.addItem(conex.rs.getString("Nome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preecher Fornecedor");
        }
     BDconexao.fecharConexao(con);
    }
         public void PreencherTabelaFactuas(String sql){
             ArrayList dados=new ArrayList();
             String[] colunas=new String[]{"Artigo","Descricao","Quantidade","Iva","Preco/Unitario","Total"};
             con=BDconexao.getconnection();
             conex.executaSql(sql);
       try {
           conex.rs.first();
           do{
           dados.add(new Object[]{conex.rs.getString(conex.rs.getInt("codTipoProduto")),conex.rs.getString("Descr"),conex.rs.getInt("Quantidade"),conex.rs.getFloat("Iva")
                   ,conex.rs.getDouble("PrecUnit"),conex.rs.getDouble("Total")});
           
           }while(conex.rs.next());
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Busque novamente");
       }
         Tabela modelo=new Tabela(dados,colunas);
         
         jTableFacturas.setModel(modelo);
         
         jTableFacturas.getColumnModel().getColumn(0).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(0).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(1).setPreferredWidth(200);
         jTableFacturas.getColumnModel().getColumn(1).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(2).setPreferredWidth(100);
         jTableFacturas.getColumnModel().getColumn(2).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(3).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(3).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(4).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(5).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(6).setPreferredWidth(200);
         jTableFacturas.getColumnModel().getColumn(6).setResizable(false);
   
         BDconexao.fecharConexao(con);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }
    
  
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonCopiar;
    private javax.swing.JButton jButtonEstatistica;
    private javax.swing.JButton jButtonFeramentas;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNova;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVendas;
    private javax.swing.JButton jButton_Copiar;
    private javax.swing.JButton jButton_Gravar;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Imprimir;
    private javax.swing.JButton jButton_Novo;
    private javax.swing.JButton jButton_Procurar;
    private javax.swing.JButton jButtonfornecedor;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JComboBox<String> jComboBox_Entidade;
    private javax.swing.JComboBox<String> jComboBox_Entidade1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabel_Desconto;
    private javax.swing.JLabel jLabel_Iva;
    private javax.swing.JLabel jLabel_Mercadorias;
    private javax.swing.JLabel jLabel_Outros;
    private javax.swing.JLabel jLabel_Subtotal;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCatProd;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCompras;
    private javax.swing.JPanel jPanelFacturar;
    private javax.swing.JPanel jPanelFornecedor;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelMenuVendas;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JPanel jPanel_TabelaVendas;
    private javax.swing.JPanel jPanel_TermosPagamento;
    private javax.swing.JPanel jPanel_Valores;
    private javax.swing.JPanel jPanel_Vendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane_Entidade;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner_dataEmissao;
    private javax.swing.JSpinner jSpinner_dataVencimento;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableFacturas;
    private javax.swing.JTable jTableFacturas1;
    private javax.swing.JTable jTableForncedor;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextField_DescontoFinanceiro;
    private javax.swing.JTextField jTextField_IVA;
    private javax.swing.JTextField jTextField_Mercadorias;
    private javax.swing.JTextField jTextField_Outros;
    private javax.swing.JTextField jTextField_Subtotal;
    private javax.swing.JTextField jTextField_Total;
    private javax.swing.JButton jbNovaFactura;
    private javax.swing.JButton jbNovaVenda;
    // End of variables declaration//GEN-END:variables
}
