/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.BDconexao;
import Model.Dao.FornecedorDAO;
import Model.Entidade.Fornecedor;
import Model.Entidade.Tabela;
import static View.PaginaLogin.usuario;
import java.awt.CardLayout;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author JEQUE
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    
   FornecedorDAO fdao=new FornecedorDAO();
   Fornecedor fmode=new Fornecedor();
   BDconexao conex=new BDconexao();
   Connection con;
   int n;
   
   
   int flag=0;
    CardLayout cardLayout;
    
    
    public PaginaInicial() {
        initComponents();
        cardLayout=(CardLayout)(jPanelPrincipal.getLayout());
     jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[]{usuario.getNome(), "Perfil", "Sair"}));
        upTime(jLabel11);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelInicial = new javax.swing.JPanel();
        jLabelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelVendas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jbNovaFactura = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jbNovaVenda = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanelCompras = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableFacturas1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanelFactura = new javax.swing.JPanel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEmpresa = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldArtigo = new javax.swing.JTextField();
        jTextFieldPrecUnit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jTextFieldDisconto = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jButtonPesquisa1 = new javax.swing.JButton();
        jTextFieldPesquisa1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jPanelFacturar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanelFornecedor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableForncedor = new javax.swing.JTable();
        jButtonPesquisa = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonVendas = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jButtonfornecedor = new javax.swing.JButton();
        jButtonEstatistica = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonNova = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCopiar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonFeramentas = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemCatProd = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestao de Facturas");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Hora");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 440, 110, 15);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelInicial.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFundo.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addComponent(jLabelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelInicial, "telaInicial");

        jPanelVendas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artigo", "Descricao", "descricao", "Iva", "Preco/Unidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFacturas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jbNovaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jbNovaFactura.setOpaque(false);
        jbNovaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaFacturaActionPerformed(evt);
            }
        });

        jLabel19.setText("nova factura");

        jButton3.setText("Pesuisa");

        jbNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jbNovaVenda.setOpaque(false);
        jbNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaVendaActionPerformed(evt);
            }
        });

        jLabel18.setText("nova venda");

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jbNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(164, 164, 164)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasLayout.createSequentialGroup()
                .addGroup(jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbNovaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jLabel18))
                    .addComponent(jbNovaVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelVendas, "telaVendas");

        jPanelCompras.setBackground(new java.awt.Color(255, 255, 255));

        jTableFacturas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artigo", "Descricao", "descricao", "Iva", "Preco/Unidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableFacturas1);

        jButton4.setText("Pesuisa");

        javax.swing.GroupLayout jPanelComprasLayout = new javax.swing.GroupLayout(jPanelCompras);
        jPanelCompras.setLayout(jPanelComprasLayout);
        jPanelComprasLayout.setHorizontalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComprasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanelComprasLayout.setVerticalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComprasLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelCompras, "telaCompras");

        jPanelFactura.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxFornecedor.setAutoscrolls(true);
        jComboBoxFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jComboBoxFornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFornecedorItemStateChanged(evt);
            }
        });
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });

        jTextAreaEmpresa.setEditable(false);
        jTextAreaEmpresa.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextAreaEmpresa.setRows(5);
        jTextAreaEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jScrollPane3.setViewportView(jTextAreaEmpresa);

        jButton1.setBackground(new java.awt.Color(235, 235, 235));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(235, 235, 235));
        jButtonCancel.setText("Cancelar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Produto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Preco/Unitario");

        jTextFieldProduto.setEditable(false);
        jTextFieldProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jTextFieldArtigo.setEditable(false);
        jTextFieldArtigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jTextFieldPrecUnit.setEditable(false);
        jTextFieldPrecUnit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Quantidade");

        jTextFieldQtd.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jTextFieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tipo");

        jTextFieldTipo.setEditable(false);
        jTextFieldTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Validade");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Artigo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Desconto");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Sub-Total");

        jTextFieldSubTotal.setEditable(false);
        jTextFieldSubTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jTextFieldDisconto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jTextFieldDisconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiscontoActionPerformed(evt);
            }
        });

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total");

        jXDatePicker1.setPreferredSize(new java.awt.Dimension(4, 18));
        jXDatePicker1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPrecUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDisconto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTotal)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrecUnit)
                            .addComponent(jLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQtd)
                            .addComponent(jLabel5))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDisconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldArtigo, jTextFieldDisconto, jTextFieldSubTotal});

        jButtonPesquisa1.setBackground(new java.awt.Color(235, 235, 235));
        jButtonPesquisa1.setText("Pesquisar");
        jButtonPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisa1ActionPerformed(evt);
            }
        });

        jTextFieldPesquisa1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jScrollPane4.setBackground(new java.awt.Color(51, 255, 204));

        jTableProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableProduto);

        javax.swing.GroupLayout jPanelFacturaLayout = new javax.swing.GroupLayout(jPanelFactura);
        jPanelFactura.setLayout(jPanelFacturaLayout);
        jPanelFacturaLayout.setHorizontalGroup(
            jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFacturaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanelFacturaLayout.createSequentialGroup()
                        .addGroup(jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFornecedor, 0, 209, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanelFacturaLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelFacturaLayout.setVerticalGroup(
            jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturaLayout.createSequentialGroup()
                .addGroup(jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa1))
                .addGap(8, 8, 8)
                .addGroup(jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFacturaLayout.createSequentialGroup()
                        .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelFactura, "telaNovaFactura");

        jPanelFacturar.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setText("Enviar");

        jButton11.setText("Voltar");

        javax.swing.GroupLayout jPanelFacturarLayout = new javax.swing.GroupLayout(jPanelFacturar);
        jPanelFacturar.setLayout(jPanelFacturarLayout);
        jPanelFacturarLayout.setHorizontalGroup(
            jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacturarLayout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(25, 25, 25))
        );
        jPanelFacturarLayout.setVerticalGroup(
            jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacturarLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(jPanelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelFacturar, "telaFacturar");

        jPanelFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableForncedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jTableForncedor.setOpaque(false);
        jTableForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableForncedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableForncedor);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Capturar.PNG"))); // NOI18N
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFornecedorLayout = new javax.swing.GroupLayout(jPanelFornecedor);
        jPanelFornecedor.setLayout(jPanelFornecedorLayout);
        jPanelFornecedorLayout.setHorizontalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPanelFornecedorLayout.setVerticalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisa))
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelFornecedor, "telaFornecedor");

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(200, 50, 750, 408);

        jPanel2.setBackground(new java.awt.Color(220, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jButtonVendas.setBackground(new java.awt.Color(201, 201, 201));
        jButtonVendas.setText("Vendas");
        jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVendas);
        jButtonVendas.setBounds(0, 0, 200, 32);

        jButtonCompras.setBackground(new java.awt.Color(201, 201, 201));
        jButtonCompras.setText("Compras");
        jButtonCompras.setFocusable(false);
        jButtonCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCompras);
        jButtonCompras.setBounds(0, 30, 200, 30);

        jButtonfornecedor.setBackground(new java.awt.Color(201, 201, 201));
        jButtonfornecedor.setText("Fornecedores");
        jButtonfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonfornecedor);
        jButtonfornecedor.setBounds(0, 60, 200, 30);

        jButtonEstatistica.setBackground(new java.awt.Color(201, 201, 201));
        jButtonEstatistica.setText("Estatistica");
        jPanel2.add(jButtonEstatistica);
        jButtonEstatistica.setBounds(0, 90, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-2, 50, 200, 140);

        jPanel3.setBackground(new java.awt.Color(220, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jButtonNova.setToolTipText("Nova factura");
        jButtonNova.setOpaque(false);
        jButtonNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        jButtonSalvar.setOpaque(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/copy.png"))); // NOI18N
        jButtonCopiar.setOpaque(false);
        jButtonCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        jButton6.setOpaque(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jButton7.setOpaque(false);

        jButtonFeramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/settings.png"))); // NOI18N
        jButtonFeramentas.setOpaque(false);
        jButtonFeramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeramentasActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(235, 235, 235));
        jButtonHome.setText("Home");
        jButtonHome.setFocusable(false);
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setOpaque(false);
        jButtonHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jComboBoxUsuario.setBackground(new java.awt.Color(235, 235, 235));
        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Perfil", "Sair" }));
        jComboBoxUsuario.setOpaque(false);
        jComboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButtonCancelar.setOpaque(false);

        jLabel12.setText("salvar");

        jLabel13.setText("nova");

        jLabel14.setText("Copiar");

        jLabelImprimir.setText("Imprimir");

        jLabel16.setText("Cancelar");

        jLabel17.setText("Ferramentas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHome)
                .addGap(146, 146, 146)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jButtonNova, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelImprimir)
                .addGap(32, 32, 32)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(24, 24, 24)
                .addComponent(jButtonFeramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonHome)
                                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonFeramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNova, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 950, 40);

        jPanel5.setBackground(new java.awt.Color(220, 250, 250));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 950, 480);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu7.setText("file");

        jMenu1.setText("Cadastros");

        jMenuItemUsuario.setText("Usuarios");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuario);

        jMenuItemFornecedor.setText("Fornecedores");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFornecedor);

        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProduto);

        jMenuItemCatProd.setText("Categoria de produtos");
        jMenuItemCatProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCatProdActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCatProd);

        jMenu7.add(jMenu1);

        jMenuItem3.setText("sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Operacoes");

        jMenu2.setText("Facturas ");
        jMenu6.add(jMenu2);

        jMenu3.setText("Fornecedores");
        jMenu6.add(jMenu3);

        jMenu4.setText("Compra");
        jMenu6.add(jMenu4);

        jMenu5.setText("Venda");
        jMenu6.add(jMenu5);

        jMenuBar1.add(jMenu6);

        jMenuSair.setText("Ajuda");

        jMenuItem2.setText("Pagina Inicial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem2);

        jMenuItem1.setText("Acerca");
        jMenuSair.add(jMenuItem1);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(966, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
      FormUsuario telaU=new FormUsuario();
      telaU.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemCatProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCatProdActionPerformed
       FormCategoria telaC=new FormCategoria();
       telaC.setVisible(true);
    }//GEN-LAST:event_jMenuItemCatProdActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
       FormFornecedor telaF=new FormFornecedor();
       telaF.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        FormProduto telaP=new FormProduto();
        telaP.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jTableForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableForncedorMouseClicked
        /*String nome=""+jTableForncedor.getValueAt(jTableForncedor.getSelectedRow(),1);
        con=BDconexao.getconnection();
        conex.executaSql("Select *from Fornecedor where Nome='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldCod.setText(String.valueOf(conex.rs.getInt("CodFornecedor")));
            jTextFieldNome.setText(conex.rs.getString("Nome"));
            jTextFieldEndereco.setText(conex.rs.getString("Endereco"));
            jTextFieldTelefone.setText(String.valueOf(conex.rs.getInt("Telefone")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro Ao preecher do MauseClicked");
        }
        BDconexao.fecharConexao(con);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);*/

    }//GEN-LAST:event_jTableForncedorMouseClicked

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        fmode.setPesquisa(jTextFieldPesquisa.getText());
        //Fornecedor model=fdao.BuscaFornecedor(fmode);
        jTextFieldPesquisa.setText("");
        PreencherTabela("Select *from Fornecedor where nome like'%"+fmode.getPesquisa()+"%'");
        /**jTextFieldNome.setText(model.getNome());
        jTextFieldEndereco.setText(model.getEndereco());
        jTextFieldTelefone.setText(String.valueOf(model.getTelefone()));*/

    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       FormEmpresa telaE=new FormEmpresa();
       telaE.setVisible(true);
               

        /*flag=1;
        jButtonSalvar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);

        jTextFieldCod.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldTelefone.setText("");

        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisa.setEnabled(false);*/
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfornecedorActionPerformed
       cardLayout.show(jPanelPrincipal,"telaFornecedor");
       PreencherTabela("Select *from Fornecedor order by Nome");
    }//GEN-LAST:event_jButtonfornecedorActionPerformed

    private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
        cardLayout.show(jPanelPrincipal,"telaVendas");
    }//GEN-LAST:event_jButtonVendasActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed
        cardLayout.show(jPanelPrincipal,"telaCompras");
       
        
    }//GEN-LAST:event_jButtonComprasActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
     jTextAreaEmpresa.setText("");
        fmode.setPesquisa(""+jComboBoxFornecedor.getSelectedItem());
        Fornecedor f=fdao.BuscaFornecedor(fmode);
        
       jTextAreaEmpresa.insert( f.getEndereco(), jTextAreaEmpresa.getCaretPosition());
       jTextAreaEmpresa.append("\n");
       jTextAreaEmpresa.insert( String.valueOf(f.getTelefone()),jTextAreaEmpresa.getCaretPosition());
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        String nome=""+jTableProduto.getValueAt(jTableProduto.getSelectedRow(),1);
        con=BDconexao.getconnection();

        conex.executaSql("SELECT CodProduto,Descr,CodFornecedor,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
            + "NATURAL JOIN produto NATURAL join tipoproduto where descr='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldArtigo.setText(String.valueOf(conex.rs.getInt("CodProduto")));
            jTextFieldProduto.setText(conex.rs.getString("Descr"));
            jTextFieldQtd.setText("1");
            // jComboBoxFornecedor.setSelectedItem(conex.rs.getString("Nome"));
            jTextFieldPrecUnit.setText(String.valueOf(conex.rs.getDouble("PrecoUnit")));
            jTextFieldTipo.setText(conex.rs.getString("DescrTipoProduto"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro Ao preecher do MauseClicked");
        }
        BDconexao.fecharConexao(con);
    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jButtonPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisa1ActionPerformed
        fmode.setPesquisa(jTextFieldPesquisa1.getText());
       jTextFieldPesquisa1.setText("");
        PreencherTabelaProduto("SELECT CodProduto,Descr,CodFornecedor,Nome,PrecoUnit,DescrTipoProduto from Fornecedor "
               + "NATURAL JOIN produto NATURAL join tipoproduto where descr like '%"+fmode.getPesquisa()+"'");
        
    }//GEN-LAST:event_jButtonPesquisa1ActionPerformed
  
       
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        cardLayout.show(jPanelPrincipal,"telaInicial");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cardLayout.show(jPanelPrincipal,"telaFacturar");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioActionPerformed
       switch (jComboBoxUsuario.getSelectedIndex()) {
            case 2:
                
                dispose();
               PaginaLogin p=new PaginaLogin();
               p.setVisible(rootPaneCheckingEnabled);
                break;
        }
    }//GEN-LAST:event_jComboBoxUsuarioActionPerformed

    private void jComboBoxFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorItemStateChanged
       jTextAreaEmpresa.setText("");
        fmode.setPesquisa(""+jComboBoxFornecedor.getSelectedItem());
        Fornecedor f=fdao.BuscaFornecedor(fmode);
        
       jTextAreaEmpresa.insert( f.getEndereco(), jTextAreaEmpresa.getCaretPosition());
       jTextAreaEmpresa.append("\n");
       jTextAreaEmpresa.insert( String.valueOf(f.getTelefone()),jTextAreaEmpresa.getCaretPosition());
    }//GEN-LAST:event_jComboBoxFornecedorItemStateChanged

    private void jButtonNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaActionPerformed
        cardLayout.show(jPanelPrincipal,"telaNovaFactura");
        preencherFornecedor();
    }//GEN-LAST:event_jButtonNovaActionPerformed

    private void jButtonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCopiarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       cardLayout.show(jPanelPrincipal,"telaInicial");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonFeramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeramentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeramentasActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jbNovaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaFacturaActionPerformed
       cardLayout.show(jPanelPrincipal,"telaNovaFactura");
        preencherFornecedor();
    }//GEN-LAST:event_jbNovaFacturaActionPerformed

    private void jbNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNovaVendaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         
       
         
         
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
               float a=Float.parseFloat(jTextFieldQtd.getText());
               float b=Float.parseFloat(jTextFieldPrecUnit.getText());
                String str=""+a*b;
               jTextFieldSubTotal.setText(str);
               jTextFieldTotal.setText(jTextFieldSubTotal.getText());
                                             
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTextFieldDiscontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiscontoActionPerformed
       
       jTextFieldTotal.setText(jTextFieldSubTotal.getText());
        
    }//GEN-LAST:event_jTextFieldDiscontoActionPerformed
     public void upTime(JLabel jlHora) {
        new Thread() {
            
            @Override
            public void run() {
                while (true) {
                    try {
                        jlHora.setText(new Time(System.currentTimeMillis()).toString());
                        sleep(1000);
                    } catch (InterruptedException e) {
                        JOptionPane.showMessageDialog(jlHora, "Erro actualizar a hoara, Erro F006");
                    }
                }
            }
        }.start();
    }
    
    
    public void PreencherTabela(String sql){
    ArrayList dados=new ArrayList();
    String[] colunas=new String[]{"ID","Nome","Endereco","Telefone"};
    con=BDconexao.getconnection();
    conex.executaSql(sql);
    try{
    conex.rs.first();
    do{
       dados.add(new Object[]{conex.rs.getInt("CodFornecedor"),conex.rs.getString("Nome"),
       conex.rs.getString("Endereco"),conex.rs.getInt("Telefone")});
      
    }while(conex.rs.next());
    }catch(SQLException ex){
    
       JOptionPane.showMessageDialog(null,"Busque novamente");
    } 
    Tabela modelo=new Tabela(dados,colunas);
  
   
    jTableForncedor.setModel(modelo);
    jTableForncedor.getColumnModel().getColumn(0).setPreferredWidth(80);
    jTableForncedor.getColumnModel().getColumn(0).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(1).setPreferredWidth(241);
    jTableForncedor.getColumnModel().getColumn(1).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(2).setPreferredWidth(300);
    jTableForncedor.getColumnModel().getColumn(2).setResizable(false);
     jTableForncedor.getColumnModel().getColumn(3).setPreferredWidth(80);
    jTableForncedor.getColumnModel().getColumn(3).setResizable(false);
    jTableForncedor.getTableHeader().setReorderingAllowed(false);
    jTableForncedor.setAutoResizeMode(jTableForncedor.AUTO_RESIZE_OFF);
    jTableForncedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
    BDconexao.fecharConexao(con);
    }
     public void PreencherTabelaProduto(String sql){
    ArrayList dados=new ArrayList();
    String[] colunas=new String[]{"ID","Descr","CodFornecedor","Fornecedor","PrecUnit","Tipo"};
    con=BDconexao.getconnection();
    conex.executaSql(sql);
    try{
    conex.rs.first();
    do{
       dados.add(new Object[]{conex.rs.getInt("CodProduto"),conex.rs.getString("Descr"),
       conex.rs.getString("CodFornecedor"),conex.rs.getString("Nome"),conex.rs.getInt("PrecoUnit"),
       conex.rs.getString("DescrTipoProduto")});
      
    }while(conex.rs.next());
    }catch(SQLException ex){
    
       JOptionPane.showMessageDialog(null,"Busque novamente");
    } 
    Tabela modelo=new Tabela(dados,colunas);
  
   
    jTableProduto.setModel(modelo);
    jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(60);
    jTableProduto.getColumnModel().getColumn(0).setResizable(false);
     jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(250);
    jTableProduto.getColumnModel().getColumn(1).setResizable(false);
     jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
    jTableProduto.getColumnModel().getColumn(2).setResizable(false);
     jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(110);
    jTableProduto.getColumnModel().getColumn(3).setResizable(false);
     jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(80);
    jTableProduto.getColumnModel().getColumn(4).setResizable(false);
     jTableProduto.getColumnModel().getColumn(5).setPreferredWidth(110);
    jTableProduto.getColumnModel().getColumn(5).setResizable(false);
    jTableProduto.getTableHeader().setReorderingAllowed(false);
    jTableProduto.setAutoResizeMode(jTableProduto.AUTO_RESIZE_OFF);
    jTableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
    BDconexao.fecharConexao(con);
    }
    
    public void preencherFornecedor(){
    con=BDconexao.getconnection();
    conex.executaSql("Select *from Fornecedor order by Nome");
        try {
            conex.rs.first();
            
               jComboBoxFornecedor.removeAllItems();
            do{
                jComboBoxFornecedor.addItem(conex.rs.getString("Nome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preecher Fornecedor");
        }
     BDconexao.fecharConexao(con);
    }
         public void PreencherTabelaFactuas(String sql){
             ArrayList dados=new ArrayList();
             String[] colunas=new String[]{"Artigo","Descricao","Quantidade","Iva","Preco/Unitario","Total"};
             con=BDconexao.getconnection();
             conex.executaSql(sql);
       try {
           conex.rs.first();
           do{
           dados.add(new Object[]{conex.rs.getString(conex.rs.getInt("codTipoProduto")),conex.rs.getString("Descr"),conex.rs.getInt("Quantidade"),conex.rs.getFloat("Iva")
                   ,conex.rs.getDouble("PrecUnit"),conex.rs.getDouble("Total")});
           
           }while(conex.rs.next());
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Busque novamente");
       }
         Tabela modelo=new Tabela(dados,colunas);
         
         jTableFacturas.setModel(modelo);
         
         jTableFacturas.getColumnModel().getColumn(0).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(0).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(1).setPreferredWidth(200);
         jTableFacturas.getColumnModel().getColumn(1).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(2).setPreferredWidth(100);
         jTableFacturas.getColumnModel().getColumn(2).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(3).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(3).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(4).setPreferredWidth(80);
         jTableFacturas.getColumnModel().getColumn(5).setResizable(false);
         jTableFacturas.getColumnModel().getColumn(6).setPreferredWidth(200);
         jTableFacturas.getColumnModel().getColumn(6).setResizable(false);
   
         BDconexao.fecharConexao(con);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }
    
  
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonCopiar;
    private javax.swing.JButton jButtonEstatistica;
    private javax.swing.JButton jButtonFeramentas;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNova;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonPesquisa1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVendas;
    private javax.swing.JButton jButtonfornecedor;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCatProd;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCompras;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JPanel jPanelFacturar;
    private javax.swing.JPanel jPanelFornecedor;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableFacturas;
    private javax.swing.JTable jTableFacturas1;
    private javax.swing.JTable jTableForncedor;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextArea jTextAreaEmpresa;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldArtigo;
    private javax.swing.JTextField jTextFieldDisconto;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPesquisa1;
    private javax.swing.JTextField jTextFieldPrecUnit;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldTotal;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton jbNovaFactura;
    private javax.swing.JButton jbNovaVenda;
    // End of variables declaration//GEN-END:variables
}
